import Head from "next/head";
import LoginForm from "../components/LoginForm";

export default function Home() {
  return (
    <div className="flex flex-col justify-around items-center">
      <Head>
        <title>캡스톤</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1
        className="relative flex items-center justify-center p-2 w-40 h-10 mx-auto rounded-lg
       bg-purple-400 text-lg font-bold top-32"
      >
        팀명
      </h1>

      <LoginForm />
    </div>
  );
}
