import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>캡스톤</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="absolute top-[33%] w-full flex justify-center ">
        렌트허브
      </h1>

      <main className="absolute top-[45%] flex w-full justify-center space-x-4 ">
        <div>
          <Link href="/login">로그인</Link>
        </div>
        <div>
          <Link href="/register">회원가입</Link>
        </div>
      </main>

      <Link href="/homepage">개발용 버튼</Link>
    </div>
  );
}
