import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { useForm } from "react-hook-form";
import Axios from "axios";
import { useRouter } from "next/router";
import { useEffect } from "react";

import { useAuthState } from "../context/auth";

export default function Home() {
  // react hook form
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm();

  const router = useRouter();
  const { userEmail, useEmailFetch, setUserEmail } = useAuthState();

  useEmailFetch();

  const onSubmit = async (data, e) => {
    e.preventDefault();

    const url = "http://110.12.218.147:8080/api/v1/user/login";

    data = {
      email: data.email,
      password: data.password,
    };

    try {
      const res = await Axios.post(
        url,
        {
          email: data.email,
          password: data.password,
        },
        {
          withCredentials: true,
        }
      );

      if (res.data.result === "success") {
        localStorage.setItem(
          "auth",
          JSON.stringify({ ...res.data, email: data.email })
        );
        setUserEmail(data.email);
        router.push("/homepage");
        reset();
      } else {
        alert("다시 로그인 해주세요");
      }
    } catch (err) {
      console.log(err);
    } finally {
      reset();
    }
  };

  if (!!userEmail) {
    router.push("/homepage");
  }

  if (!userEmail) {
    return (
      <div>
        <Head>
          <title>캡스톤</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex h-screen items-center justify-between">
          {/*image*/}
          <div className="ml-40 basis-2/5 relative h-4/6 overflow-hidden rounded-t-full">
            <Image
              src="/index_pic.jpg"
              layout="fill"
              objectFit="cover"
              alt="mainlogo"
            />
          </div>

          {/*로그인 회원 가입*/}
          <div className="basis-3/5 flex flex-col items-center space-y-6 w-full">
            <div className="text-7xl !z-20">렌트허브</div>
            {/* "handleSubmit" will validate your inputs before invoking "onSubmit" */}
            <form
              onSubmit={handleSubmit(onSubmit)}
              className="flex-col flex justify-center w-3/5"
            >
              <label
                htmlFor="email"
                className="block text-sm font-semibold text-gray-800"
              >
                이메일
              </label>
              <input
                type="email"
                {...register("email", { required: true })}
                className="border-2 border-gray-300 rounded-sm"
              />

              <label
                htmlFor="password"
                className="block text-sm font-semibold text-gray-800 "
              >
                비밀번호
              </label>
              <input
                {...register("password", { required: true })}
                type="password"
                className="border-2 border-gray-300 rounded-sm "
              />
              {errors.password && <span>비밀번호</span>}

              <div className="flex justify-between mt-6">
                <button
                  className="p-1 px-2 space-x-2 text- font-bold border-2
                          border-gray-400 w-fit rounded-md
                          cursor-pointer hover:border-blue-300 transition"
                  type="submit"
                >
                  로그인 하기
                </button>

                <div
                  className="p-1 px-2 space-x-2 text- font-bold border-2
                          border-gray-400 w-fit rounded-md
                          cursor-pointer hover:border-blue-300 transition"
                  type="submit"
                >
                  <Link href="/register">아직 회원 아님.. 회원가입하기</Link>
                </div>
              </div>
            </form>
          </div>
        </main>
      </div>
    );
  }
}
